### PR TITLE
Create duckspeak.py

### PR DESCRIPTION
**Pull request by Turtle1331**
This module allows for quick and easy translation, primarily intended for French and English.

### CODE REVIEW

**Comment by Diagamma** [comment]
Thanks, but even though DeepL is good, l10n is already implemented in the bot, and we prefer (well, I do) to have human-translated text than machine-translated text. Using this piece of code would also require adding more dependencies, and would add a huge latency, which is not very desirable. I had already thought about using DeepL for untranslated strings, but I don't think it's worth all the trouble, latency and stuff.
IMO, this is not a good idea, so I'm vetoing this PR. I'm not closing it though, since @paris-ci is the owner and it would be disrespectful of me to do it without letting him give his opinion.

**Comment by Turtle1331** [comment]
Thanks for the clear response.  I understand the issue with adding dependencies.  I don't get what you mean by the human-translation over machine-translation part though.  Could there still be some possibility of adding it to the server as one of the external bots?  Thank you for considering my request.

**Comment by Diagamma** [comment]
Oh right, I'm stupid. That's what I get for reviewing at 2AM. Seems like a good idea then. Sorry.
@paris-ci Yeah, please move it to its own repo. :P

**Comment by Turtle1331** [comment]
Ok, that latest commit should have fixed it.  Thanks @paris-ci for the clarification.

**Pull request merged**
